### ISSUE TITLE
Milliseconds converted incorrectly to seconds

### ISSUE THREAD

**Issue by Elijen** [fmarcia/UglifyCSS#31]
Units in ms are incorrectly converted to seconds:
```css
/* test.css */
.animated {
  animation-duration: 600ms;
}
```
```css
/* result of `uglifycss test.css` */
.animated{animation-duration:60s}
```
Expected output:
```css
.animated{animation-duration:600ms}
```
