### ISSUE TITLE
Spaces will removed in url

### ISSUE THREAD

**Issue by lazyants** [fmarcia/UglifyCSS#38]
It still seems to be an issue, all of spaces in svg/xml are missing after minifying
 ```css
img.grayscale {
	filter: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg'><filter id='grayscale'><feColorMatrix type='matrix' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale");
	filter: gray;
	-webkit-filter: grayscale(100%);
}
```

![image](https://cloud.githubusercontent.com/assets/249065/12021346/3e1a5230-ad86-11e5-9533-2ed4e5a48697.png)
