### ISSUE TITLE
0% getting transformed to 0 incorrectly and breaking keyframe animation?

### ISSUE THREAD

**Issue by edhenderson** [fmarcia/UglifyCSS#43]
```
"gulp-uglifycss": "^1.0.6",
```

```sass
@keyframes magic {
    0%, 25% { 
        transform: scale(2.25);
    }

    100% {
        transform: scale(1);
    }
}
```

gets generated to:

```css
@keyframes magic{0,25%{transform:scale(2.25)}100%{transform:scale(1)}}
```

Which browser no likey. If I manually edit the generated CSS to be `0%` it works again. Temp fix is to change the line to:

```sass
    from, 25% {
```

Any advice, input would be appreciated, thanks so much for a great tool.
