### ISSUE TITLE
Url changed after mininfied

### ISSUE THREAD

**Issue by Vasikaran** [fmarcia/UglifyCSS#53]
```
// before minify
.profile{
   background:url("../images/profile.png") no-repeat scroll 0 0 transparent;
}

// after minify
.profile{
   background:url(___PRESERVED_TOKEN_1___) no-repeat scroll 0 0 transparent;
}
```

What is this? Is this a bug?

**Comment by fmarcia** [comment]
Thanks for your feedback.
Yes, it looks like a bug.
Could you please provide the input you used?

**Comment by Vasikaran** [comment]
```
let uglifyCss = require('uglifycss');

let css  = `.profile{
   background:url("../images/profile.png") no-repeat scroll 0 0 transparent;
}`;
let minifiedCss = uglifyCss.processString(css);

console.log(minifiedCss);

// output looks like
.profile{
   background:url(___PRESERVED_TOKEN_1___) no-repeat scroll 0 0 transparent;
}
```

**Comment by jacobwindsor** [comment]
I checked and cannot replicate this using the CLI. It works as expected.

```css
// INPUT
.myClass {
	width: calc(100% + 30px);
	background:url("../images/profile.png") no-repeat scroll 0 0 transparent;
}

// OUTPUT
.myClass{width:calc(100% + 30px);background:url("../images/profile.png") no-repeat scroll 0 0 transparent}
```

Could be a bug only with the node API?
