### ISSUE TITLE
Changed keyword initial to default value

### ISSUE THREAD

**Issue by astridx** [fmarcia/UglifyCSS#73]
In my case 

```
.modal-body {
  overflow-y: initial; }
```
is changed to 
```
.modal-body {
  overflow-y: scroll; }
```

That is OK, because `initial` stands for the `default value` and `scroll` is the default value of `overflow-y`.

Nevertheless, I would like to keep  `initial`. Is that possible?

**Comment by fmarcia** [comment]
When minifying:
```css
.modal-body {
  overflow-y: initial; }
```
The result is:
```css
.modal-body{overflow-y:initial}
```
It looks like your issue is not because of uglifycss.
